import { Fraunces, Inter } from 'next/font/google';
import './globals.css';
import RootWrapper from './RootWrapper';
import QueryProvider from '@/providers/QueryProvider';
import AuthProvider from '@/providers/AuthProvider';
import ReduxProvider from '@/store/ReduxProvider';
import { Toaster } from 'sonner';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${fraunces.variable} h-full antialiased`}
    >
      <body
        className={`${inter.className} min-h-full flex flex-col bg-[#F9FAFB]`}
      >
        <QueryProvider>
          <AuthProvider>
            <ReduxProvider>
              <RootWrapper>
                {children}
                <Toaster position="bottom-right" />
              </RootWrapper>
            </ReduxProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
